### ISSUE TITLE
Won't install on Kodi 16.1(Jarvis)+ and 17 (Krypton)

### ISSUE THREAD

**Issue by dwbfox** [dwbfox/kodi-ethiopian-tv#2]
Attempting to install the .zip package in /dist for Libelec fails with an unknown error.

**Comment by aimproper28** [comment]
This message is for dwbFox... I am also trying to get as many Amharic live streams on Kodi as is possible... I am an satellite tech in San Jose ca, USA. If you would like to stay in touch about this matter, send me an email ( aimproper28@gmail.com , if you don't already know, there is ETV on Kodi...EBS WAS also on Kodi but it no longer works. I am looking forward to hearing from you:)

**Comment by dwbfox** [comment]
Hi. This is more of a pet project for me than anything else (I actually programmed it at the request of my mother). The plugin broke likely due to updates to Kodi's add-on structure and requirements. I should be able to update it to a working condition in the coming weeks.

**Comment by dwbfox** [comment]
Hi, this issue has been resolved with the latest version. Please check the /dist version and try the Krypton release.

**Comment by dwbfox** [comment]
To answer your question regarding EBS, the stream may have gone down. There's not much I can do about that other than find another source and push an update when one becomes available.

**Comment by Tdotsown** [comment]
I can send you new sources from the same provider if you like. Sne dme a personal email or tell me yours

________________________________
